; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyProductName "易點雙視 v5"
#define MyAppName "易點雙視"
#define MyAppVersion "5.0"
#define MyAppPublisher "蔡煥麟"
#define MyAppExeName "EasyBrailleEdit.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E0CAA5D1-B906-4BFD-8BA2-E9AA6C71C18F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName=C:\EasyBrailleEdit5
DefaultGroupName={#MyProductName}
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
UsePreviousAppDir=False
AllowRootDirectory=True
AllowUNCPath=False
VersionInfoCopyright=Copyright (c) 2008-2025 Michael Tsai

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "traditional_chinese"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Languages: traditional_chinese english

[Files]
Source: "Files\LICENSE.md"; DestDir: "{app}"; Flags: ignoreversion

Source: "Files\app\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "Fonts\simbrl.ttf"; DestDir: "{fonts}"; Flags: onlyifdoesntexist uninsneveruninstall; FontInstall: "SimBraille"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: "HKCR"; Subkey: ".brx"; ValueType: string; ValueData: "EasyBrailleEdit.brx"
Root: "HKCR"; Subkey: "EasyBrailleEdit.brx\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "Applications\EasyBrailleEdit.exe\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "易點雙視"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "Applications\EasyBrailleEdit.exe\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
