baseURL = 'https://braillekit.github.io/text-to-braille/'
languageCode = 'zh-tw'
title = 'EasyBrailleEdit'

contentDir = 'content'

# Set type to 'docs' if you want to render page outside of configured section or if you render section other than 'docs'
type = 'docs'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy']

[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookRepo = 'https://github.com/braillekit/text-to-braille'
  BookDateFormat = '2006年1月2日'

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"
  [module.hugoVersion]
    extended = false
    min = "0.110.0"

[menu]
  [[menu.main]]
    name = "易點雙視"
    url = "/"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
