name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for MinVer to work correctly
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Extract version from git tag
      id: get_version
      shell: pwsh
      run: |
        if ($env:GITHUB_REF -match 'refs/tags/(.+)') {
          $version = $matches[1]
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "Creating release for version $version"
        } else {
          echo "VERSION=0.0.0" >> $env:GITHUB_OUTPUT
          echo "No version tag found, using 0.0.0"
        }
    
    - name: Restore NuGet packages
      run: dotnet restore "Source\EasyBrailleEditApp\EasyBrailleEditApp.sln"
      
    - name: Build solution
      run: dotnet build "Source\EasyBrailleEditApp\EasyBrailleEditApp.sln" --configuration Release --no-restore
      
    - name: Publish EasyBrailleEdit
      run: dotnet publish "Source\EasyBrailleEditApp\EasyBrailleEdit\EasyBrailleEdit.csproj" --configuration Release --no-build --output publish\EasyBrailleEdit
    
    - name: Publish Txt2Brl
      run: dotnet publish "Source\EasyBrailleEditApp\Txt2Brl\Txt2Brl.csproj" --configuration Release --no-build --output publish\Txt2Brl

    - name: Copy Txt2Brl binaries to EasyBrailleEdit
      run: |
        $source = "publish/Txt2Brl"
        $destination = "publish\EasyBrailleEdit"
        if (Test-Path $source) {
          Copy-Item -Path $source/Txt2Brl.* -Destination $destination -Force
          Copy-Item -Path $source/CommandLine.dll -Destination $destination -Force
          Copy-Item -Path $source/sample.txt -Destination $destination -Force
          Write-Host "✅ Copied Txt2Brl binaries to EasyBrailleEdit directory."
        } else {
          Write-Error "❌ Txt2Brl executable not found at $source"
          exit 1
        }
  
    - name: Upload EasyBrailleEdit artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EasyBrailleEdit
        path: publish\EasyBrailleEdit\
        
    - name: Upload Txt2Brl artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Txt2Brl
        path: publish\Txt2Brl\

    - name: Zip EasyBrailleEdit
      if: startsWith(github.ref, 'refs/tags/')  # Only zip if this is a tag push
      shell: pwsh
      run: |
        $sourceFolder = "./publish/EasyBrailleEdit"
        $zipPath = "./publish/EasyBrailleEdit-v${{ steps.get_version.outputs.VERSION }}.zip"
        Write-Host "Compressing $sourceFolder/*  to  $zipPath"
        Compress-Archive -Path "$sourceFolder/*" -DestinationPath $zipPath -Force
        # Ensure the zip file is created.
        if (Test-Path $zipPath) {
          Write-Host "✅ Zip created at: $zipPath"
        } else {
          Write-Error "❌ Zip file not found at: $zipPath"
          exit 1
        }
            
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')  # Only create a release if this is a tag push
      uses: softprops/action-gh-release@v2
      # IMPORTANT: the path separator in the `files` input must be `/`, not `\`. Otherwise it will fail.
      # Refer to the GitHub docs: https://github.com/softprops/action-gh-release#inputs
      with:
        files: |
          publish/EasyBrailleEdit-v${{ steps.get_version.outputs.VERSION }}.zip
        name: 易點雙視 v${{ steps.get_version.outputs.VERSION }}
        body: |
          # 易點雙視 v${{ steps.get_version.outputs.VERSION }}
          
          易點雙視（EasyBrailleEdit）是一個 Windows 應用程式，主要用途是編輯與列印雙視教材，以供視障朋友摸讀。
          
          ## 本版更新內容
          
          <!-- 請在這裡填寫更新內容 -->
          
          ## 下載檔案說明
          
          - **EasyBrailleEdit-v${{ steps.get_version.outputs.VERSION }}.zip**: 雙視點字編輯器主程式
          - **Txt2Brl-v${{ steps.get_version.outputs.VERSION }}.zip**: 文字轉點字命令列工具
        draft: true