name: Build and Deploy

on:
  push:
    branches: [ v5.0.0 ]
  pull_request:
    branches: [ v5.0.0 ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release -o publish
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EasyBrailleEdit
        path: publish/